---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install AWX dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ awx_package_dependencies }}"

- name: Clone AWX into configured directory.
  git:
    repo: "{{ awx_repo }}"
    dest: "{{ awx_repo_dir }}"
    version: "{{ awx_version }}"
    update: "{{ awx_keep_updated }}"
    force: true
    accept_hostkey: true

- name: Install a secrets file for AWX.
  template:
    src: ".awx_secrets.yml.j2"
    dest: "{{ awx_secrets_path }}"
    mode: "0400"

- include: awx-install-playbook.yml
  when: awx_run_install_playbook
